### PR TITLE
eth_signTypeData_v3 hook for EIP712

### PR DESCRIPTION
**Pull request by JamesSmartCell**
Adds the EIP712 signing hook to the AlphaWallet dist.

See article here:

https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26

in particular the new hook ```eth_signTypedData_v3```.

I will create a separate issue for iOS with an in-depth 'How-To' for EIP712 and legacy EIP712 (```eth_signTypeData```), both standards are in use and we should support them.

### CODE REVIEW

**Comment by James-Sangalli** [comment]
@JamesSmartCell did you change the regular dist file then minify?

**Comment by JamesSmartCell** [comment]
Yes. Is that how it should be done? Or is there a better process?

**Comment by James-Sangalli** [comment]
> Yes. Is that how it should be done? Or is there a better process?

That is the right way (technically the builder should work but it doesn't) just wanted to clarify because checking the diff in the min file is very difficult

**Comment by hboon** [comment]
>  checking the diff in the min file is very difficult

Understatement of the year :)

**Review by James-Sangalli — APPROVED** [review]

**Comment by hboon** [comment]
Superseded by #14

**Pull request closed without merging**
